# Generated by Django 3.2.20 on 2023-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_type', models.CharField(choices=[('Happiness', 'Happiness'), ('Hope', 'Hope'), ('Love', 'Love'), ('Surprise', 'Surprise'), ('Empathy', 'Empathy'), ('Pride', 'Pride'), ('Sadness', 'Sadness'), ('Anger', 'Anger'), ('Fear', 'Fear'), ('Guilt', 'Guilt')], max_length=200)),
                ('quote', models.TextField(max_length=500)),
            ],
        ),
    ]
