# Generated by Django 3.2.20 on 2023-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='emotion_type',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_category',
            field=models.CharField(choices=[('Happiness', 'Happiness'), ('Hope', 'Hope'), ('Love', 'Love'), ('Surprise', 'Surprise'), ('Empathy', 'Empathy'), ('Pride', 'Pride'), ('Sadness', 'Sadness'), ('Anger', 'Anger'), ('Fear', 'Fear'), ('Fact', 'Fact'), ('Guit', 'Guilt'), ('Growth', 'Growth'), ('Success', 'Success')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
