# Generated by Django 3.2.20 on 2023-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20230813_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_category',
            field=models.CharField(choices=[('', 'Category'), ('Happiness', 'Happiness'), ('Hope', 'Hope'), ('Love', 'Love'), ('Surprise', 'Surprise'), ('Empathy', 'Empathy'), ('Pride', 'Pride'), ('Sadness', 'Sadness'), ('Anger', 'Anger'), ('Fear', 'Fear'), ('Fact', 'Fact'), ('Guit', 'Guilt'), ('Growth', 'Growth'), ('Success', 'Success')], max_length=200),
        ),
    ]
