# Generated by Django 3.2.20 on 2023-08-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_quote_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='owned_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_category',
            field=models.CharField(choices=[('', 'Category'), ('Happiness', 'Happiness'), ('Hope', 'Hope'), ('Love', 'Love'), ('Surprise', 'Surprise'), ('Empathy', 'Empathy'), ('Pride', 'Pride'), ('Beauty', 'Beauty'), ('Sadness', 'Sadness'), ('Anger', 'Anger'), ('Fear', 'Fear'), ('Fact', 'Fact'), ('Guit', 'Guilt'), ('Growth', 'Growth'), ('Success', 'Success')], max_length=200),
        ),
    ]
