# Generated by Django 3.2.20 on 2023-08-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20230813_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
