# Generated by Django 3.2.20 on 2023-08-17 15:01

from django.db import migrations
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=quotes.models.ExtendedSlugField(max_length=500, unique=True),
        ),
    ]
