# Generated by Django 3.2.20 on 2024-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_quote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_category',
            field=models.CharField(choices=[('', 'Category'), ('Happiness', 'Happiness'), ('Hope', 'Hope'), ('Life', 'Life'), ('Emotion', 'Emotion'), ('Empathy', 'Empathy'), ('Pride', 'Pride'), ('Beauty', 'Beauty'), ('Sadness', 'Sadness'), ('Anger', 'Anger'), ('Discipline', 'Discipline'), ('Fact', 'Fact'), ('Guit', 'Guilt'), ('Growth', 'Growth'), ('Success', 'Success')], max_length=200),
        ),
    ]
